# Generated by Django 5.2.7 on 2025-10-22 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(help_text='Currency of this account’s balance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='catalog.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='catalog.institution'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='account.accounttype'),
        ),
    ]
