# Generated by Django 5.2.7 on 2025-11-12 20:01

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('catalog', '0003_alter_exchangeraterecord_base_currency_and_more'),
        ('common', '0003_alter_unit_preferred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('card_number', models.CharField(help_text='Last 4-6 digits of the card number for identification.', max_length=6)),
                ('card_type', models.CharField(choices=[('debit', 'Debit Card'), ('credit', 'Credit Card')], default='debit', help_text='Type of card (debit or credit).', max_length=10)),
                ('name', models.CharField(blank=True, help_text="Optional name for the card (e.g., 'Primary Debit Card', 'Travel Card').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is currently active.')),
            ],
            options={
                'ordering': ['-is_active', 'card_type', 'card_number'],
            },
            bases=(models.Model, common.models.SoftDeleteMixin),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number, card number, or other identifier (last 4-6 digits for privacy).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(help_text="Currency of this account's balance.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='common.currency'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number__isnull', False), models.Q(('account_number', ''), _negated=True)), fields=('created_by', 'account_number'), name='unique_account_number_per_user'),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(help_text='The account this card is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='account.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('account', 'card_number'), name='unique_card_number_per_account'),
        ),
    ]
