# Generated by Django 5.2.7 on 2025-10-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdummymodel',
            options={'managed': False, 'verbose_name': 'Analytics Dashboard', 'verbose_name_plural': 'Analytics Dashboard'},
        ),
    ]
