# Generated by Django 5.2.7 on 2025-10-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsdummymodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsDummyModel',
        ),
    ]
