# Generated by Django 5.2.7 on 2025-10-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_delete_analyticsdummymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Analytics Dashboard',
                'verbose_name_plural': 'Analytics Dashboard',
                'managed': False,
            },
        ),
    ]
