# Generated by Django 5.2.7 on 2025-10-22 00:25

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('email', 'Email'), ('text', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (optional).', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/attachments/', location='media/attachments'), upload_to='attachments/')),
                ('text_content', models.TextField(blank=True, help_text='Raw text or parsed content.', null=True)),
                ('source_url', models.URLField(blank=True, help_text='Optional source URL (e.g., web receipt or email link).', null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(choices=[('weight', 'Weight'), ('length', 'Length'), ('volume', 'Volume'), ('pieces', 'Pieces')], max_length=20)),
                ('conversion_to_base', models.FloatField(blank=True, null=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='common.unit')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='common.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
