# Generated by Django 5.2.7 on 2025-10-23 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Currency code (ISO 4217 or symbol like BTC)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('type', models.CharField(choices=[('fiat', 'Fiat Currency'), ('crypto', 'Cryptocurrency')], default='fiat', max_length=10)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_to_base', models.DecimalField(decimal_places=8, default=1, help_text='Conversion rate to system base currency.', max_digits=18)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Only one should be base.')),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(choices=[('weight', 'Weight'), ('length', 'Length'), ('volume', 'Volume'), ('pieces', 'Pieces')], max_length=20)),
                ('conversion_to_base', models.FloatField(blank=True, null=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='common.unit')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='common.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
