# Generated by Django 5.2.7 on 2025-10-30 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_unit_preferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='preferred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='common.unit'),
        ),
    ]
