# Generated by Django 5.2.7 on 2025-11-18 10:04

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_unit_preferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Friendly name used in the app.', max_length=128, unique=True)),
                ('provider', models.CharField(help_text='e.g., Google, OpenAI, Anthropic.', max_length=64)),
                ('model_id', models.CharField(help_text='Exact identifier required by the provider.', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='Optional provider-specific key.', max_length=255, null=True)),
                ('type', models.CharField(choices=[('text', 'Text-only'), ('multimodal', 'Multimodal'), ('speech', 'Speech / TTS'), ('vision', 'Vision / Image')], default='text', max_length=32)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers = preferred for failover.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['provider', 'model_id'], name='common_aimo_provide_ca7c44_idx')],
            },
            bases=(models.Model, common.models.SoftDeleteMixin),
        ),
    ]
