# Generated by Django 5.2.7 on 2025-10-19 21:57

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('preferred', models.ForeignKey(blank=True, help_text='If this is a variant spelling, link to the canonical brand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='bills.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='categories', to='bills.categorygroup')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='bills.purchasecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='bills.purchasecategory')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='bills.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/bills/', location='media/bills'), upload_to='')),
                ('processed', models.BooleanField(default=False)),
                ('store_name_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('purchase_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='bills.purchasecategory')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='bills.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(choices=[('weight', 'Weight'), ('length', 'Length'), ('volume', 'Volume'), ('pieces', 'Pieces')], max_length=20)),
                ('conversion_to_base', models.FloatField(blank=True, help_text='Multiply by this factor to convert to base unit. (1 if itself is base)', null=True)),
                ('base_unit', models.ForeignKey(blank=True, help_text='Base or canonical unit for this measurement type (e.g. g, m, L, pcs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='bills.unit')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='bills.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.ForeignKey(blank=True, help_text='The brand this item belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bills.brand')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='bills.itemname')),
                ('preferred_unit', models.ForeignKey(blank=True, help_text='Default or most common unit for this item (e.g. grams, liters, pieces).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_items', to='bills.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_name_raw', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('unit_raw', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill')),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='bills.itemname')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='bills.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
