# Generated by Django 5.2.7 on 2025-10-22 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('catalog', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('transfer_credit', 'Transfer_Credit'), ('transfer_debit', 'Transfer_Debit')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, help_text='Upload a receipt, invoice, or any related file', null=True, upload_to='transactions/attachments/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='account.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='catalog.purchasecategory')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalog.currency')),
                ('exchange_rate_record', models.ForeignKey(blank=True, help_text='Exchange rate details for this transfer (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.exchangeraterecord')),
                ('fee', models.ForeignKey(blank=True, help_text='Link to fee transaction associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_for_transactions', to='transaction.transaction')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_transfer', to='transaction.transaction')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='catalog.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(default=1)),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='catalog.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.transaction')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
