# Generated by Django 5.2.7 on 2025-10-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('common', '0001_initial'),
        ('transaction', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.ForeignKey(blank=True, help_text='Attachment linked to this transaction (e.g., receipt, invoice, bill).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user.attachment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='catalog.purchasecategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='common.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_record',
            field=models.ForeignKey(blank=True, help_text='Exchange rate details for this transfer (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.exchangeraterecord'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.ForeignKey(blank=True, help_text='Link to fee transaction associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_for_transactions', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_transfer', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='catalog.store'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.unit'),
        ),
    ]
