# Generated by Django 5.2.7 on 2025-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='totals_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
