# Generated by Django 5.2.7 on 2025-10-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_totals_match_alter_transactionitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='totals_match',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
