# Generated by Django 5.2.7 on 2025-11-11 23:01

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_totals_match'),
        ('user', '0007_alter_emailsyncjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTransactionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_id', models.CharField(db_index=True, help_text='Unique Gmail message ID (from Gmail API).', max_length=128)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('email_timestamp', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gmail_account', models.ForeignKey(help_text='Gmail account this email belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mapped_transactions', to='user.gmailaccount')),
                ('job', models.ForeignKey(blank=True, help_text='Email sync job that processed this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_transactions', to='user.emailsyncjob')),
                ('transaction', models.ForeignKey(help_text='Linked financial transaction parsed from this email.', on_delete=django.db.models.deletion.CASCADE, related_name='email_mappings', to='transaction.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_id'], name='transaction_email_i_9a75c8_idx'), models.Index(fields=['gmail_account', 'email_id'], name='transaction_gmail_a_5b1a40_idx')],
                'unique_together': {('gmail_account', 'email_id', 'transaction')},
            },
            bases=(models.Model, common.models.SoftDeleteMixin),
        ),
    ]
