# Generated by Django 5.2.7 on 2025-11-16 22:57

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_totals_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('transfer_credit', 'Transfer IN'), ('transfer_debit', 'Transfer OUT')], max_length=16),
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount this user owes', max_digits=12)),
                ('has_paid', models.BooleanField(default=False, help_text='Whether this user has paid their share')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this split', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(help_text='The transaction this split belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='transaction.transaction')),
                ('user', models.ForeignKey(help_text='The user who owes this amount', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Split',
                'verbose_name_plural': 'Transaction Splits',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'user')},
            },
            bases=(models.Model, common.models.SoftDeleteMixin),
        ),
    ]
