# Generated by Django 5.2.7 on 2025-11-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_card_account_account_number_alter_account_currency_and_more'),
        ('transaction', '0005_emailtransactionmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, help_text='The card used for this transaction (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='account.card'),
        ),
    ]
