# Generated by Django 5.2.7 on 2025-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_transaction_type_transactionsplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwesDummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Owes',
                'verbose_name_plural': 'Owes',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='transactionsplit',
            name='has_paid',
        ),
    ]
