# Generated by Django 5.2.7 on 2025-10-22 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Currency code (ISO 4217 or symbol like BTC)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('type', models.CharField(choices=[('fiat', 'Fiat Currency'), ('crypto', 'Cryptocurrency')], default='fiat', max_length=10)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_to_base', models.DecimalField(decimal_places=8, default=1, help_text='Conversion rate to system base currency.', max_digits=18)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Only one should be base.')),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card Issuer'), ('broker', 'Investment / Brokerage'), ('insurance', 'Insurance'), ('fintech', 'Fintech / Wallet'), ('other', 'Other')], default='bank', max_length=30)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('market_rate', models.DecimalField(blank=True, decimal_places=8, help_text='Mid-market rate at the time (e.g. ECB or CoinGecko)', max_digits=20, null=True)),
                ('provider_rate', models.DecimalField(decimal_places=8, help_text='Actual rate used by the institution performing the conversion', max_digits=20)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=0, help_text='Markup percentage between market and provider rate', max_digits=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_currency', models.ForeignKey(help_text='Currency being converted from', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('quote_currency', models.ForeignKey(help_text='Currency being converted to', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currency')),
                ('provider', models.ForeignKey(blank=True, help_text='Institution or service provider that executed the exchange (e.g. Revolut, Wise, Binance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.brand')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
