# Generated by Django 5.2.7 on 2025-10-22 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_items', to='common.unit'),
        ),
        migrations.AddField(
            model_name='purchasecategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.categorygroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.purchasecategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stores', to='catalog.purchasecategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='preferred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.store'),
        ),
    ]
