# Generated by Django 5.2.7 on 2025-10-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeraterecord',
            name='base_currency',
            field=models.ForeignKey(help_text='Currency being converted from', on_delete=django.db.models.deletion.PROTECT, related_name='base_exchange_records', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='exchangeraterecord',
            name='quote_currency',
            field=models.ForeignKey(help_text='Currency being converted to', on_delete=django.db.models.deletion.PROTECT, related_name='quoted_exchange_records', to='common.currency'),
        ),
    ]
