# Generated by Django 5.2.7 on 2025-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gemini_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
