# Generated by Django 5.2.7 on 2025-11-10 21:42

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_gemini_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('creds', models.JSONField()),
                ('last_history_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('created_by', 'email_address')},
            },
            bases=(models.Model, common.models.SoftDeleteMixin),
        ),
    ]
