# Generated by Django 5.2.7 on 2025-11-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_gmailaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emails', models.IntegerField(default=0)),
                ('analysed_count', models.IntegerField(default=0)),
                ('potential_tx_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('successful_tx_count', models.IntegerField(default=0)),
                ('last_email_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_tx_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching'), ('analysing', 'Analysing'), ('parsing', 'Parsing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='user.gmailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
