# Generated by Django 5.2.7 on 2025-11-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_emailsyncjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsyncjob',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='emailsyncjob',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsyncjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsyncjob',
            name='next_page_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailsyncjob',
            name='partial_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
