# Generated by Django 5.2.7 on 2025-11-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_updated_at_emailsyncjob_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsyncjob',
            name='user',
        ),
    ]
