# Generated by Django 5.2.7 on 2025-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_emailsyncjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsyncjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching'), ('analysing', 'Analysing'), ('parsing', 'Parsing'), ('done', 'Done'), ('paused', 'Paused'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
